simulation:
  host: "localhost"
  port: 64256
  home: "C:\\Users\\user\\Documents\\BeamNG.tech.v0.38.5.0"
  deterministic_fps: 60

perception:
  enable_cv_lane_detection: true
  enable_object_detection: true
  enable_traffic_light_detection: true
  enable_sign_detection: true
  enable_yolop: true

vehicles:
  etk800:
    name: "etk_egovehicle"
    model: "etk800"
    license: "JULIAN"

  q8_andronisk:
    name: "q8_egovehicle"
    model: "q8_andronisk"
    license: "JULIAN"
    part_config: "main.pc"
