control:

  steering_pid:
    Kp: 0.10
    Ki: 0.001
    Kd: 0.03
    Kf: 0.015

  max_steering_change: 0.22
  target_speed_kph: 50
  min_gap: 10.0

  speed_control_mode: cruise # options: 'manual', 'adaptive', 'cruise'

  speed_pid:
    Kp: 0.02
    Ki: 0.0
    Kd: 0.01
